-- Modular Holoconstructor
function c444415.initial_effect(c)
	local e3=Effect.CreateEffect(c)
	e3:SetType(EFFECT_TYPE_ACTIVATE)
	e3:SetCode(EVENT_FREE_CHAIN)
	c:RegisterEffect(e3)
    local e4=Effect.CreateEffect(c)
	e4:SetDescription(aux.Stringid(444415,0))
	e4:SetCategory(CATEGORY_SPECIAL_SUMMON+CATEGORY_TOKEN)
	e4:SetType(EFFECT_TYPE_IGNITION)
	e4:SetRange(LOCATION_ONFIELD+LOCATION_PZONE)
	e4:SetCountLimit(1)
	e4:SetCondition(c444415.condition)
	e4:SetCost(c444415.spcost2)
	e4:SetTarget(c444415.sptg2)
	e4:SetOperation(c444415.spop2)
	c:RegisterEffect(e4)
end
function c444415.filter(c)
	return c:IsSetCard(4444) and c:IsAbleToGraveAsCost()
end

function c444415.condition(e,tp,eg,ep,ev,re,r,rp)
	return Duel.IsExistingMatchingCard(c444415.filter,tp,LOCATION_DECK,0,1,nil) and Duel.GetFlagEffect(tp,e:GetHandler():GetCode())<2 	
end
function c444415.spcost2(e,tp,eg,ep,ev,re,r,rp,chk)
	if chk==0 then return Duel.IsExistingMatchingCard(c444415.filter,tp,LOCATION_DECK,0,1,e:GetHandler(),tp) end
	local g=Duel.SelectMatchingCard(tp,c444415.filter,tp,LOCATION_DECK,0,1,1,e:GetHandler(),tp)
	Duel.SendtoGrave(g,REASON_COST)
	local effectcopy=g:GetFirst()
	e:SetLabelObject(effectcopy)
	Duel.RegisterFlagEffect(tp,e:GetHandler():GetCode(),RESET_EVENT+0x007e0000+RESET_PHASE+PHASE_END,0,1)
end
function c444415.sptg2(e,tp,eg,ep,ev,re,r,rp,chk)
	if chk==0 then return Duel.GetLocationCount(tp,LOCATION_MZONE)>0
		and Duel.IsPlayerCanSpecialSummonMonster(tp,444444,0,0x4011,0,0,3,16777216,ATTRIBUTE_LIGHT) end
	Duel.SetOperationInfo(0,CATEGORY_TOKEN,nil,1,0,0)
	Duel.SetOperationInfo(0,CATEGORY_SPECIAL_SUMMON,nil,1,0,0)
end
function c444415.spop2(e,tp,eg,ep,ev,re,r,rp)
	if Duel.GetLocationCount(tp,LOCATION_MZONE)<=0 then return end
	if Duel.IsPlayerCanSpecialSummonMonster(tp,444444,0,0x4011,0,0,3,16777216,ATTRIBUTE_LIGHT) then
	local token=Duel.CreateToken(tp,444444)
	Duel.SpecialSummon(token,0,tp,tp,false,false,POS_FACEUP_ATTACK)
	local e1=Effect.CreateEffect(e:GetHandler())
	e1:SetType(EFFECT_TYPE_SINGLE)
	e1:SetCode(EFFECT_UNRELEASABLE_SUM)
	e1:SetValue(1)
	e1:SetReset(RESET_EVENT+0x007e0000)
	token:RegisterEffect(e1,true)
	local e2=e1:Clone()
	e2:SetCode(EFFECT_UNRELEASABLE_NONSUM)
	token:RegisterEffect(e2,true)
    local e3=e1:Clone()
	e3:SetCode(EFFECT_INDESTRUCTABLE)
	e3:SetCondition(c444415.tokendescon) 
	token:RegisterEffect(e3,true)
	local e4=e1:Clone()
	e4:SetCode(EFFECT_CANNOT_BE_EFFECT_TARGET)
	token:RegisterEffect(e4,true)
	local e5=e1:Clone()
	e5:SetCode(EFFECT_CANNOT_BE_FUSION_MATERIAL)
	token:RegisterEffect(e5,true)
	local e5=e1:Clone()
	e5:SetCode(EFFECT_CANNOT_BE_SYNCHRO_MATERIAL)
	token:RegisterEffect(e5,true)
	local e6=e1:Clone()
	e6:SetCode(EFFECT_CANNOT_BE_XYZ_MATERIAL)
	token:RegisterEffect(e6,true)
	local e7=e1:Clone()
	e7:SetCode(EFFECT_CANNOT_ATTACK)
    token:RegisterEffect(e7,true)
    local tc=e:GetLabelObject(effectcopy)   
    local code=tc:GetOriginalCodeRule()
    local cid=0
    cid=token:CopyEffect(code,RESET_EVENT+0x007e0000+RESET_PHASE+PHASE_STANDBY,2)
	local e8=Effect.CreateEffect(e:GetHandler())                
    e8:SetDescription(aux.Stringid(444415,1))
    e8:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_CONTINUOUS)
    e8:SetCode(EVENT_PHASE+PHASE_STANDBY+RESET_SELF_TURN)
    e8:SetProperty(EFFECT_FLAG_CANNOT_DISABLE+EFFECT_FLAG_UNCOPYABLE)
    e8:SetCountLimit(1)
    e8:SetRange(LOCATION_ONFIELD)
    e8:SetReset(RESET_EVENT+0x007e0000+RESET_PHASE+PHASE_STANDBY,2)
    e8:SetLabel(cid)
    e8:SetOperation(c444415.rstop)
    token:RegisterEffect(e8,true)
    local e10=Effect.CreateEffect(e:GetHandler())
	e10:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_CONTINUOUS)
	e10:SetProperty(EFFECT_FLAG_IGNORE_IMMUNE+EFFECT_FLAG_CANNOT_DISABLE+EFFECT_FLAG_UNCOPYABLE)
	e10:SetRange(LOCATION_ONFIELD)
	e10:SetCode(EVENT_PHASE+PHASE_STANDBY)
	e10:SetOperation(c444415.desop)
	e10:SetCondition(c444415.descon)
	e10:SetReset(RESET_EVENT+0x007e0000+RESET_PHASE+PHASE_STANDBY,2)
	e10:SetCountLimit(1)
	token:RegisterEffect(e10,true)
	Duel.SpecialSummonComplete()
	end
end
function c444415.rstop(e,tp,eg,ep,ev,re,r,rp)
    local c=e:GetHandler()
    local cid=e:GetLabel()
    if cid~=0 then c:ResetEffect(cid,RESET_COPY) end
    Duel.HintSelection(Group.FromCards(c))
    Duel.Hint(HINT_OPSELECTED,tp,e:GetDescription())
    c:ResetEffect(cid,RESET_CARD)
end
function c444415.desop(e,tp,eg,ep,ev,re,r,rp)
	Duel.Destroy(e:GetHandler(),REASON_EFFECT)
end
function c444415.descon(e,tp,eg,ep,ev,re,r,rp)
	local c=e:GetHandler()
	return c:GetTurnID()~=Duel.GetTurnCount() and tp==Duel.GetTurnPlayer()
end
function c444415.tokendescon(e,tp,eg,ep,ev,re,r,rp)
	local c=e:GetHandler()
	return (re and re:GetOwner()~=c) or c:IsReason(REASON_BATTLE)
end