--Apocalisse Antilementale
--Script by XGlitchy30
local function getID()
	local str=string.match(debug.getinfo(2,'S')['source'],"c%d+%.lua")
	str=string.sub(str,1,string.len(str)-4)
	local cod=_G[str]
	local id=tonumber(string.sub(str,2))
	return id,cod
end
local id,cid=getID()
function cid.initial_effect(c)
	--Activate
	local e1=Effect.CreateEffect(c)
	e1:SetType(EFFECT_TYPE_ACTIVATE)
	e1:SetCode(EVENT_FREE_CHAIN)
	c:RegisterEffect(e1)
	--disable
	local e2=Effect.CreateEffect(c)
	e2:SetType(EFFECT_TYPE_FIELD)
	e2:SetRange(LOCATION_FZONE)
	e2:SetCode(EFFECT_DISABLE)
	e2:SetTargetRange(LOCATION_ONFIELD,0)
	e2:SetTarget(cid.disable)
	c:RegisterEffect(e2)
	--wind effect
	local e3=Effect.CreateEffect(c)
	e3:SetType(EFFECT_TYPE_FIELD)
	e3:SetProperty(EFFECT_FLAG_IGNORE_IMMUNE)
	e3:SetCode(EFFECT_CANNOT_BE_EFFECT_TARGET)
	e3:SetRange(LOCATION_MZONE)
	e3:SetLabel(ATTRIBUTE_WIND)
	e3:SetTargetRange(LOCATION_MZONE,0)
	e3:SetTarget(aux.TargetBoolFunction(Card.IsAttribute,ATTRIBUTE_WIND))
	e3:SetValue(aux.tgoval)
	local e3x=Effect.CreateEffect(c)
	e3x:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_GRANT)
	e3x:SetRange(LOCATION_FZONE)
	e3x:SetTargetRange(LOCATION_MZONE,LOCATION_MZONE)
	e3x:SetTarget(cid.eftg)
	e3x:SetLabelObject(e3)
	c:RegisterEffect(e3x)
	--earth effect
	local e4=Effect.CreateEffect(c)
	e4:SetType(EFFECT_TYPE_FIELD)
	e4:SetCode(EFFECT_INDESTRUCTABLE_BATTLE)
	e4:SetRange(LOCATION_MZONE)
	e4:SetLabel(ATTRIBUTE_EARTH)
	e4:SetTargetRange(LOCATION_MZONE,0)
	e4:SetTarget(aux.TargetBoolFunction(Card.IsAttribute,ATTRIBUTE_EARTH))
	e4:SetValue(1)
	local e4a=e4:Clone()
	e4a:SetCode(EFFECT_INDESTRUCTABLE_EFFECT)
	local e4x=Effect.CreateEffect(c)
	e4x:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_GRANT)
	e4x:SetRange(LOCATION_FZONE)
	e4x:SetTargetRange(LOCATION_MZONE,LOCATION_MZONE)
	e4x:SetTarget(cid.eftg)
	e4x:SetLabelObject(e4)
	c:RegisterEffect(e4x)
	local e4y=Effect.CreateEffect(c)
	e4y:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_GRANT)
	e4y:SetRange(LOCATION_FZONE)
	e4y:SetTargetRange(LOCATION_MZONE,LOCATION_MZONE)
	e4y:SetTarget(cid.eftg)
	e4y:SetLabelObject(e4a)
	c:RegisterEffect(e4y)
	--fire effect
	local e5=Effect.CreateEffect(c)
	e5:SetType(EFFECT_TYPE_FIELD)
	e5:SetCode(EFFECT_CANNOT_REMOVE)
	e5:SetRange(LOCATION_MZONE)
	e5:SetLabel(ATTRIBUTE_FIRE)
	e5:SetTargetRange(LOCATION_MZONE,0)
	e5:SetTarget(aux.TargetBoolFunction(Card.IsAttribute,ATTRIBUTE_FIRE))
	local e5x=Effect.CreateEffect(c)
	e5x:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_GRANT)
	e5x:SetRange(LOCATION_FZONE)
	e5x:SetTargetRange(LOCATION_MZONE,LOCATION_MZONE)
	e5x:SetTarget(cid.eftg)
	e5x:SetLabelObject(e5)
	c:RegisterEffect(e5x)
	local e5a=Effect.CreateEffect(c)
	e5a:SetType(EFFECT_TYPE_FIELD)
	e5a:SetRange(LOCATION_MZONE)
	e5a:SetCode(EFFECT_UNRELEASABLE_SUM)
	e5a:SetLabel(ATTRIBUTE_FIRE)
	e5a:SetTargetRange(LOCATION_MZONE,0)
	e5a:SetTarget(aux.TargetBoolFunction(Card.IsAttribute,ATTRIBUTE_FIRE))
	local e5b=e5a:Clone()
	e5b:SetCode(EFFECT_UNRELEASABLE_NONSUM)
	local e5y=Effect.CreateEffect(c)
	e5y:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_GRANT)
	e5y:SetRange(LOCATION_FZONE)
	e5y:SetTargetRange(LOCATION_MZONE,LOCATION_MZONE)
	e5y:SetTarget(cid.eftg)
	e5y:SetLabelObject(e5a)
	c:RegisterEffect(e5y)
	local e5z=Effect.CreateEffect(c)
	e5z:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_GRANT)
	e5z:SetRange(LOCATION_FZONE)
	e5z:SetTargetRange(LOCATION_MZONE,LOCATION_MZONE)
	e5z:SetTarget(cid.eftg)
	e5z:SetLabelObject(e5b)
	c:RegisterEffect(e5z)
	--water effect
	local e6=Effect.CreateEffect(c)
	e6:SetType(EFFECT_TYPE_FIELD)
	e6:SetProperty(EFFECT_FLAG_IGNORE_IMMUNE)
	e6:SetCode(EFFECT_IMMUNE_EFFECT)
	e6:SetRange(LOCATION_MZONE)
	e6:SetLabel(ATTRIBUTE_WATER)
	e6:SetTargetRange(LOCATION_MZONE,0)
	e6:SetTarget(aux.TargetBoolFunction(Card.IsAttribute,ATTRIBUTE_WATER))
	e6:SetValue(cid.efilter)
	local e6x=Effect.CreateEffect(c)
	e6x:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_GRANT)
	e6x:SetRange(LOCATION_FZONE)
	e6x:SetTargetRange(LOCATION_MZONE,LOCATION_MZONE)
	e6x:SetTarget(cid.eftg)
	e6x:SetLabelObject(e6)
	c:RegisterEffect(e6x)
	--change stats
	local e7=Effect.CreateEffect(c)
	e7:SetDescription(aux.Stringid(id,0))
	e7:SetType(EFFECT_TYPE_IGNITION)
	e7:SetProperty(EFFECT_FLAG_CARD_TARGET)
	e7:SetRange(LOCATION_FZONE)
	e7:SetCountLimit(1,id)
	e7:SetTarget(cid.target)
	e7:SetOperation(cid.activate)
	c:RegisterEffect(e7)
end
--filters
function cid.efilter(e,re,c)
	if re:GetHandler():IsCode(id) then return false end
	if not re:IsHasProperty(EFFECT_FLAG_CARD_TARGET) then return true end
	local g=Duel.GetChainInfo(0,CHAININFO_TARGET_CARDS)
	return not g:IsContains(c)
end
function cid.relation(c,e)
	return c:IsFaceup() and c:IsRelateToEffect(e)
end
--disable
function cid.disable(e,c)
	if c:IsType(TYPE_NORMAL) and c:IsType(TYPE_MONSTER) then return false end
	return not c:IsSetCard(0xa6e) and not c:IsLevel(9) and not c:IsLink(4) and not c:IsStage(9)
end
--attribute effect
function cid.eftg(e,c)
	local seq=c:GetSequence()
	return (c:IsLevel(9) or c:IsStage(9) or c:IsLink(4)) and c:IsAttribute(e:GetLabelObject():GetLabel())
end
--change stats
function cid.filter(c)
	return c:IsSetCard(0xa6e) and c:IsType(TYPE_MONSTER) and c:IsFaceup()
end
function cid.target(e,tp,eg,ep,ev,re,r,rp,chk,chkc)
	if chkc then return chkc:IsControler(tp) and chkc:IsLocation(LOCATION_MZONE+LOCATION_REMOVED) and cid.filter(chkc) end
	if chk==0 then return Duel.IsExistingTarget(cid.filter,tp,LOCATION_MZONE+LOCATION_REMOVED,0,2,nil) end
	Duel.Hint(HINT_SELECTMSG,tp,HINTMSG_TARGET)
	local g=Duel.SelectTarget(tp,cid.filter,tp,LOCATION_MZONE+LOCATION_REMOVED,0,2,2,nil)
	Duel.Hint(HINT_SELECTMSG,tp,HINTMSG_RACE)
	local rc=Duel.AnnounceRace(tp,1,RACE_ALL)
	Duel.Hint(HINT_SELECTMSG,tp,HINTMSG_ATTRIBUTE)
	local att=Duel.AnnounceAttribute(tp,1,0xff)
	e:SetLabel(att)
	Duel.SetTargetParam(rc)
end
function cid.activate(e,tp,eg,ep,ev,re,r,rp)
	if not e:GetHandler():IsRelateToEffect(e) then return end
	local att=e:GetLabel()
	local rc=Duel.GetChainInfo(0,CHAININFO_TARGET_PARAM)
	local g=Duel.GetChainInfo(0,CHAININFO_TARGET_CARDS)
	local sg=g:Filter(cid.relation,nil,e)
	if sg:GetCount()<=0 then return end
	local tc=sg:GetFirst()
	while tc do
		local e1=Effect.CreateEffect(e:GetHandler())
		e1:SetType(EFFECT_TYPE_SINGLE)
		e1:SetCode(EFFECT_CHANGE_RACE)
		e1:SetProperty(EFFECT_FLAG_CANNOT_DISABLE)
		e1:SetValue(rc)
		e1:SetReset(RESET_EVENT+RESETS_STANDARD+RESET_PHASE+PHASE_END,2)
		tc:RegisterEffect(e1)
		local e2=Effect.CreateEffect(e:GetHandler())
		e2:SetType(EFFECT_TYPE_SINGLE)
		e2:SetCode(EFFECT_CHANGE_ATTRIBUTE)
		e2:SetProperty(EFFECT_FLAG_CANNOT_DISABLE)
		e2:SetValue(att)
		e2:SetReset(RESET_EVENT+RESETS_STANDARD+RESET_PHASE+PHASE_END,2)
		tc:RegisterEffect(e2)
		tc=sg:GetNext()
	end
end