--The I.I.I. Full on Attack
function c201001010.initial_effect(c)
	local e0=Effect.CreateEffect(c)
	e0:SetType(EFFECT_TYPE_ACTIVATE)
	e0:SetCode(EVENT_FREE_CHAIN)
	c:RegisterEffect(e0)
	--This card gains these effects, based on the number of Tribute Summoned "I.I.I." monsters you control.
	--1+: Once per turn: You can reveal 1 Level 5 or higher "I.I.I." monster in your hand; during your Main Phase this turn, you can Normal Summon 1 "I.I.I." monster in addition to your Normal Summon/Set. (Even if this card leaves the field. You can only gain this effect once per turn.)
	local e1=Effect.CreateEffect(c)
	e1:SetType(EFFECT_TYPE_IGNITION)
	e1:SetRange(LOCATION_SZONE)
	e1:SetCountLimit(1)
	e1:SetLabel(0)
	e1:SetCondition(aux.AND(c201001010.con,function(e,tp) return Duel.GetFlagEffect(tp,201001010)==0 end))
	e1:SetCost(c201001010.cost)
	e1:SetTarget(c201001010.target)
	e1:SetOperation(c201001010.activate)
	c:RegisterEffect(e1)
	--2+: Level 5 or higher "I.I.I." monsters you control cannot be targeted or destroyed by your opponent's card effects.
	local e2=Effect.CreateEffect(c)
	e2:SetType(EFFECT_TYPE_FIELD)
	e2:SetCode(EFFECT_INDESTRUCTABLE_EFFECT)
	e2:SetRange(LOCATION_SZONE)
	e2:SetTargetRange(LOCATION_MZONE,0)
	e2:SetLabel(1)
	e2:SetCondition(c201001010.con)
	e2:SetTarget(aux.TargetBoolFunction(aux.OR(c201001010.cfilter,Card.IsPublic)))
	e2:SetValue(aux.indoval)
	c:RegisterEffect(e2)
	local e3=e2:Clone()
	e3:SetCode(EFFECT_CANNOT_BE_EFFECT_TARGET)
	e3:SetProperty(EFFECT_FLAG_IGNORE_IMMUNE)
	e3:SetValue(aux.tgoval)
	c:RegisterEffect(e3)
	--3: Level 5 or higher "I.I.I." monsters you control make a second attack during each Battle Phase.
	local e4=Effect.CreateEffect(c)
	e4:SetType(EFFECT_TYPE_FIELD)
	e4:SetCode(EFFECT_EXTRA_ATTACK)
	e4:SetRange(LOCATION_SZONE)
	e4:SetTargetRange(LOCATION_MZONE,0)
	e4:SetTarget(aux.TargetBoolFunction(aux.OR(c201001010.cfilter,Card.IsPublic)))
	e4:SetValue(1)
	c:RegisterEffect(e4)
end
function c201001010.filter(c)
	return c:IsSummonType(SUMMON_TYPE_ADVANCE) and c:IsSetCard(0xdbd)
end
function c201001010.con(e,tp,eg,ep,ev,re,r,rp)
	return Duel.GetMatchingGroupCount(c201001010.filter,tp,LOCATION_MZONE,0,nil)>e:GetLabel()
end
function c201001010.cfilter(c)
	return c:IsSetCard(0xdbd) and c:IsLevelAbove(5) and not c:IsPublic()
end
function c201001010.cost(e,tp,eg,ep,ev,re,r,rp,chk)
	if chk==0 then return Duel.IsExistingMatchingCard(c201001010.cfilter,tp,LOCATION_HAND,0,1,nil) end
	Duel.Hint(HINT_SELECTMSG,tp,HINTMSG_CONFIRM)
	local g=Duel.SelectMatchingCard(tp,c201001010.cfilter,tp,LOCATION_HAND,0,1,1,nil)
	Duel.ConfirmCards(1-tp,g)
	Duel.ShuffleHand(tp)
end
function c201001010.target(e,tp,eg,ep,ev,re,r,rp,chk)
	if chk==0 then return Duel.IsPlayerCanSummon(tp) and Duel.IsPlayerCanAdditionalSummon(tp) end
end
function c201001010.activate(e,tp,eg,ep,ev,re,r,rp)
	if not e:GetHandler():IsRelateToEffect(e) then return end
	local e1=Effect.CreateEffect(e:GetHandler())
	e1:SetDescription(aux.Stringid(201001010,2))
	e1:SetType(EFFECT_TYPE_FIELD)
	e1:SetCode(EFFECT_EXTRA_SUMMON_COUNT)
	e1:SetTargetRange(LOCATION_HAND+LOCATION_MZONE,0)
	e1:SetTarget(aux.TargetBoolFunction(Card.IsSetCard,0x8e))
	e1:SetReset(RESET_PHASE+PHASE_END)
	Duel.RegisterEffect(e1,tp)
	Duel.RegisterFlagEffect(tp,201001010,RESET_PHASE+PHASE_END,0,1)
end
