--created & coded by Lyris, art by GENZOMAN of DeviantArt
--襲雷神ズース
local cid,id=GetID()
function cid.initial_effect(c)
	local e1=Effect.CreateEffect(c)
	e1:SetType(EFFECT_TYPE_ACTIVATE)
	e1:SetCode(EVENT_FREE_CHAIN)
	c:RegisterEffect(e1)
	local e2=Effect.CreateEffect(c)
	e2:SetType(EFFECT_TYPE_SINGLE)
	e2:SetCode(EFFECT_TRAP_ACT_IN_HAND)
	e2:SetCondition(cid.handcon)
	c:RegisterEffect(e2)
	local e3=Effect.CreateEffect(c)
	e3:SetType(EFFECT_TYPE_FIELD)
	e3:SetCode(EFFECT_MUST_ATTACK)
	e3:SetRange(LOCATION_SZONE)
	e3:SetTargetRange(LOCATION_MZONE,LOCATION_MZONE)
	c:RegisterEffect(e3)
	c:EnableCounterPermit(0x921)
	local e2=Effect.CreateEffect(c)
	e2:SetType(EFFECT_TYPE_CONTINUOUS+EFFECT_TYPE_FIELD)
	e2:SetCode(EVENT_ATTACK_ANNOUNCE)
	e2:SetRange(LOCATION_SZONE)
	e2:SetOperation(cid.acop)
	c:RegisterEffect(e2)
	local e4=Effect.CreateEffect(c)
	e4:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_TRIGGER_F)
	e4:SetCode(EVENT_ATTACK_ANNOUNCE)
	e4:SetRange(LOCATION_SZONE)
	e4:SetCountLimit(1,id)
	e4:SetCategory(CATEGORY_DESTROY)
	e4:SetCondition(function() return Duel.GetAttacker():IsSetCard(0x7c4) end)
	e4:SetOperation(function() local tc=Duel.GetAttacker() if tc:IsAttackable() and not tc:IsStatus(STATUS_ATTACK_CANCELED) then Duel.Destroy(tc,REASON_EFFECT) end end)
	c:RegisterEffect(e4)
	local e5=Effect.CreateEffect(c)
	e5:SetType(EFFECT_TYPE_SINGLE+EFFECT_TYPE_TRIGGER_F)
	e5:SetCode(EVENT_DESTROYED)
	e5:SetCondition(function(e) return e:GetHandler():GetCounter(0x921)>=5 end)
	e5:SetOperation(function(e,tp) local ph=PHASE_MAIN1 if Duel.GetCurrentPhase()>ph then ph=PHASE_MAIN2 end Duel.SkipPhase(1-tp,ph,RESET_PHASE+PHASE_END,1) end)
	c:RegisterEffect(e5)
end
function cid.hfilter(c)
	return c:IsFaceup() and c:IsSetCard(0x7c4)
end
function cid.handcon(e)
	local tp=e:GetHandlerPlayer()
	return Duel.GetFieldGroupCount(tp,LOCATION_ONFIELD,0)==2 and Duel.IsExistingMatchingCard(cid.hfilter,tp,LOCATION_ONFIELD,0,2,nil)
end
function cid.acop(e,tp,eg,ep,ev,re,r,rp)
	local a,d=Duel.GetAttacker(),Duel.GetAttackTarget()
	if d and d:IsFaceup() and d:IsSetCard(0x7c4) or a:IsSetCard(0x7c4) then
		e:GetHandler():AddCounter(0x921,1)
	end
end
