--Over-wind Planetarium
function c26064007.initial_effect(c)
    c:EnableCounterPermit(0xb6)
    --Activate
    local e1=Effect.CreateEffect(c)
    e1:SetDescription(aux.Stringid(26064007,0))
    e1:SetType(EFFECT_TYPE_ACTIVATE)
    e1:SetCode(EVENT_FREE_CHAIN)
    e1:SetOperation(c26064007.activate)
    c:RegisterEffect(e1)
    --counter
    local e2=Effect.CreateEffect(c)
    e2:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_CONTINUOUS)
    e2:SetProperty(EFFECT_FLAG_DELAY)
    e2:SetCode(EVENT_FLIP_SUMMON_SUCCESS)
    e2:SetRange(LOCATION_FZONE)
    e2:SetOperation(c26064007.ctop)
    c:RegisterEffect(e2)
    local e3=e2:Clone()
    e3:SetCode(EVENT_SPSUMMON_SUCCESS)
    c:RegisterEffect(e3)
    local e4=e2:Clone()
    e4:SetCode(EVENT_SUMMON_SUCCESS)
    c:RegisterEffect(e4)
    local e5=e2:Clone()
    e5:SetCode(EVENT_DRAW)
    c:RegisterEffect(e5)
--Singularity
    local e6=Effect.CreateEffect(c)
    e6:SetType(EFFECT_TYPE_FIELD)
    e6:SetProperty(EFFECT_FLAG_PLAYER_TARGET)
    e6:SetCode(26064007)
    e6:SetRange(LOCATION_FZONE)
    e6:SetTargetRange(1,1)
    c:RegisterEffect(e6)
end
function c26064007.limit(e,c)
    return not c:IsType(TYPE_FLIP) and not c:IsSetCard(0x664)
end
function c26064007.aclimit(e,re,tp)
    local rc=re:GetHandler()
    return not rc:IsSetCard(0x664) and not re:IsActiveType(TYPE_FLIP)
end
function c26064007.activate(e,tp,eg,ep,ev,re,r,rp)
    local c=e:GetHandler()
    local g=Duel.GetMatchingGroup(Card.IsAbleToDeck,tp,LOCATION_ONFIELD+LOCATION_HAND,0,c,c)
    if g:GetCount()>0 and not Duel.IsPlayerAffectedByEffect(1-tp,EFFECT_SKIP_TURN) then
        Duel.Hint(HINT_SELECTMSG,tp,HINTMSG_TODECK)
        local sg=g:Select(tp,1,1,nil)
        Duel.HintSelection(sg)
        tg=sg:GetFirst()
        if tg and Duel.SendtoDeck(tg,nil,0,REASON_EFFECT) then
            local e1=Effect.CreateEffect(c)
            e1:SetType(EFFECT_TYPE_FIELD)
            e1:SetProperty(EFFECT_FLAG_PLAYER_TARGET)
            e1:SetCode(EFFECT_SKIP_TURN)
            e1:SetTargetRange(0,1)
            e1:SetReset(RESET_PHASE+PHASE_END+RESET_OPPO_TURN)
            Duel.RegisterEffect(e1,tp)
            local e2=Effect.CreateEffect(c)
            e2:SetType(EFFECT_TYPE_FIELD)
            e2:SetCode(EFFECT_CANNOT_SPECIAL_SUMMON)
            e2:SetProperty(EFFECT_FLAG_PLAYER_TARGET+EFFECT_FLAG_OATH)
            e2:SetTargetRange(1,0)
            e2:SetTarget(c26064007.limit)
            e2:SetReset(RESET_PHASE+PHASE_END,3)
            Duel.RegisterEffect(e2,tp)
            local e3=e2:Clone()
            e3:SetCode(EFFECT_CANNOT_ACTIVATE)
            e3:SetTarget(c26064007.aclimit)
            Duel.RegisterEffect(e3,tp)
            local e4=Effect.CreateEffect(c)
            e4:SetType(EFFECT_TYPE_FIELD)
            e4:SetCode(EFFECT_CANNOT_ATTACK)
            e4:SetTargetRange(LOCATION_MZONE,0)
            e4:SetTarget(c26064007.limit)
            e4:SetReset(RESET_PHASE+PHASE_END,3)
            Duel.RegisterEffect(e4,tp)
            --cannot activate
            local e5=Effect.CreateEffect(c)
            e5:SetType(EFFECT_TYPE_FIELD)
            e5:SetCode(EFFECT_CANNOT_ACTIVATE)
            e5:SetProperty(EFFECT_FLAG_PLAYER_TARGET)
            e5:SetTargetRange(1,0)
            e5:SetValue(c26064007.afilter)
            e5:SetReset(RESET_PHASE+PHASE_END,3)
            Duel.RegisterEffect(e5,tp)
            --cannot set
            local e6=Effect.CreateEffect(c)
            e6:SetType(EFFECT_TYPE_FIELD)
            e6:SetCode(EFFECT_CANNOT_SSET)
            e6:SetProperty(EFFECT_FLAG_PLAYER_TARGET)
            e6:SetTargetRange(1,0)
            e6:SetTarget(c26064007.sfilter)
            e6:SetReset(RESET_PHASE+PHASE_END,3)
            Duel.RegisterEffect(e6,tp)
        end
    end
end
function c26064007.afilter(e,re,tp)
    return re:GetHandler():IsType(TYPE_FIELD) and re:IsHasType(EFFECT_TYPE_ACTIVATE)
end
function c26064007.sfilter(e,c,tp)
    return c:IsType(TYPE_FIELD) and Duel.GetFieldCard(tp,LOCATION_SZONE,5)~=nil
end
function c26064007.ctop(e,tp,eg,ep,ev,re,r,rp)
    Duel.Hint(HINT_CARD,0,26064007)
    local ct=eg:GetCount()
    e:GetHandler():AddCounter(0xb6,ct)
end

function c26064007.spfilter(c,e,sp)
    return c:IsType(TYPE_FLIP) and c:IsCanBeSpecialSummoned(e,0,tp,false,false)
end