--D.D. Dragon - Ultima Sentry
function c32083046.initial_effect(c)
	--link summon
	aux.AddLinkProcedure(c,aux.FilterBoolFunction(Card.IsLinkSetCard,0x7D53),3)
	c:EnableReviveLimit()
		--cannot release
	local e1=Effect.CreateEffect(c)
	e1:SetType(EFFECT_TYPE_FIELD)
	e1:SetCode(EFFECT_CANNOT_RELEASE)
	e1:SetProperty(EFFECT_FLAG_PLAYER_TARGET)
	e1:SetRange(LOCATION_MZONE)
	e1:SetTargetRange(0,1)
	e1:SetTarget(c32083046.rellimit)
	c:RegisterEffect(e1)
		local e2=Effect.CreateEffect(c)
	e2:SetType(EFFECT_TYPE_FIELD)
	e2:SetProperty(EFFECT_FLAG_PLAYER_TARGET)
	e2:SetCode(EFFECT_CANNOT_SPECIAL_SUMMON)
	e2:SetCondition(c32083046.fcondition)
	e2:SetTarget(c32083046.flimit)
	e2:SetRange(LOCATION_MZONE)
	e2:SetTargetRange(0,1)
	c:RegisterEffect(e2)
	local e3=e2:Clone()
	e3:SetCode(EFFECT_CANNOT_SUMMON)
	c:RegisterEffect(e3)
	local e4=e2:Clone()
	e4:SetCode(EFFECT_CANNOT_FLIP_SUMMON)
	c:RegisterEffect(e4)
		local e5=Effect.CreateEffect(c)
	e5:SetType(EFFECT_TYPE_FIELD)
	e5:SetProperty(EFFECT_FLAG_PLAYER_TARGET)
	e5:SetCode(EFFECT_CANNOT_SPECIAL_SUMMON)
	e5:SetCondition(c32083046.scondition)
	e5:SetTarget(c32083046.slimit)
	e5:SetRange(LOCATION_MZONE)
	e5:SetTargetRange(0,1)
	c:RegisterEffect(e5)
	local e6=e5:Clone()
	e6:SetCode(EFFECT_CANNOT_SUMMON)
	c:RegisterEffect(e6)
	local e7=e6:Clone()
	e7:SetCode(EFFECT_CANNOT_FLIP_SUMMON)
	c:RegisterEffect(e7)
		local e8=Effect.CreateEffect(c)
	e8:SetType(EFFECT_TYPE_FIELD)
	e8:SetProperty(EFFECT_FLAG_PLAYER_TARGET)
	e8:SetCode(EFFECT_CANNOT_SPECIAL_SUMMON)
	e8:SetCondition(c32083046.xcondition)
	e8:SetTarget(c32083046.xlimit)
	e8:SetRange(LOCATION_MZONE)
	e8:SetTargetRange(0,1)
	c:RegisterEffect(e8)
	local e9=e8:Clone()
	e9:SetCode(EFFECT_CANNOT_SUMMON)
	c:RegisterEffect(e9)
	local e10=e9:Clone()
	e10:SetCode(EFFECT_CANNOT_FLIP_SUMMON)
	c:RegisterEffect(e10)
		local e11=Effect.CreateEffect(c)
	e11:SetType(EFFECT_TYPE_FIELD)
	e11:SetProperty(EFFECT_FLAG_PLAYER_TARGET)
	e11:SetCode(EFFECT_CANNOT_SPECIAL_SUMMON)
	e11:SetCondition(c32083046.lcondition)
	e11:SetTarget(c32083046.llimit)
	e11:SetRange(LOCATION_MZONE)
	e11:SetTargetRange(0,1)
	c:RegisterEffect(e11)
	local e12=e11:Clone()
	e12:SetCode(EFFECT_CANNOT_SUMMON)
	c:RegisterEffect(e12)
	local e13=e12:Clone()
	e13:SetCode(EFFECT_CANNOT_FLIP_SUMMON)
	c:RegisterEffect(e13)
end
function c32083046.rellimit(e,c,tp,sumtp)
	return c==e:GetHandler()
end
function c32083046.flimit(e,c,sump,sumtype,sumpos,targetp,se)
	return c:IsType(TYPE_FUSION)
end
function c32083046.ffilter(c)
	return c:IsFaceup() and c:IsType(TYPE_FUSION) and c:IsSetCard(0x7D53)
end
function c32083046.fcondition(e)
	return Duel.IsExistingMatchingCard(c32083046.ffilter,e:GetHandlerPlayer(),LOCATION_MZONE,0,1,e:GetHandler())
end
function c32083046.slimit(e,c,sump,sumtype,sumpos,targetp,se)
	return c:IsType(TYPE_SYNCHRO)
end
function c32083046.sfilter(c)
	return c:IsFaceup() and c:IsType(TYPE_SYNCHRO) and c:IsSetCard(0x7D53)
end
function c32083046.scondition(e)
	return Duel.IsExistingMatchingCard(c32083046.sfilter,e:GetHandlerPlayer(),LOCATION_MZONE,0,1,e:GetHandler())
end
function c32083046.xlimit(e,c,sump,sumtype,sumpos,targetp,se)
	return c:IsType(TYPE_XYZ)
end
function c32083046.xfilter(c)
	return c:IsFaceup() and c:IsType(TYPE_XYZ) and c:IsSetCard(0x7D53)
end
function c32083046.xcondition(e)
	return Duel.IsExistingMatchingCard(c32083046.xfilter,e:GetHandlerPlayer(),LOCATION_MZONE,0,1,e:GetHandler())
end
function c32083046.llimit(e,c,sump,sumtype,sumpos,targetp,se)
	return c:IsType(TYPE_LINK)
end
function c32083046.lfilter(c)
	return c:IsFaceup() and c:IsType(TYPE_LINK) and c:IsSetCard(0x7D53)
end
function c32083046.lcondition(e)
	return Duel.IsExistingMatchingCard(c32083046.lfilter,e:GetHandlerPlayer(),LOCATION_MZONE,0,1,e:GetHandler())
end