--Mana, Cactsun Girl of Fiber VINE
function c50031699.initial_effect(c)
		local e1=Effect.CreateEffect(c)
	e1:SetDescription(aux.Stringid(50031699,0))
	e1:SetCategory(CATEGORY_SPECIAL_SUMMON)
	e1:SetType(EFFECT_TYPE_SINGLE+EFFECT_TYPE_TRIGGER_O)
	e1:SetCode(EVENT_SUMMON_SUCCESS)
	e1:SetCountLimit(1,50031699)
	e1:SetTarget(c50031699.target)
	e1:SetOperation(c50031699.operation)
	c:RegisterEffect(e1)
		c:RegisterEffect(e1)
	local e2=e1:Clone()
	e2:SetCode(EVENT_SPSUMMON_SUCCESS)
	c:RegisterEffect(e2)
	local e3=e1:Clone()
	e3:SetCode(EVENT_FLIP_SUMMON_SUCCESS)
	c:RegisterEffect(e3)
	  local e4=Effect.CreateEffect(c)
	e4:SetDescription(aux.Stringid(50031699,0))
	e4:SetType(EFFECT_TYPE_QUICK_O)
	e4:SetCode(EVENT_FREE_CHAIN)
	e4:SetRange(LOCATION_GRAVE)
	e4:SetHintTiming(0,0x11e0)
	e4:SetProperty(EFFECT_FLAG_CARD_TARGET)
	e4:SetCountLimit(1,50031609)
	e4:SetCondition(aux.exccon)
	e4:SetCost(aux.bfgcost)
	e4:SetTarget(c50031699.target2)
	e4:SetOperation(c50031699.operation2)
	c:RegisterEffect(e4)
end
function c50031699.filter(c,e,tp)
	return c:IsType(TYPE_MONSTER) and (c:IsSetCard(0x85a) or c:IsRace(RACE_PLANT))and c:IsCanBeSpecialSummoned(e,0,tp,false,false) and not c:IsCode(50031699)
end
function c50031699.target(e,tp,eg,ep,ev,re,r,rp,chk)
	if chk==0 then return Duel.GetLocationCount(tp,LOCATION_MZONE)>0
		and Duel.IsExistingMatchingCard(c50031699.filter,tp,LOCATION_HAND+LOCATION_DECK,0,1,nil,e,tp) end
	Duel.SetOperationInfo(0,CATEGORY_SPECIAL_SUMMON,nil,1,tp,LOCATION_HAND+LOCATION_DECK)
end
function c50031699.operation(e,tp,eg,ep,ev,re,r,rp)
	if Duel.GetLocationCount(tp,LOCATION_MZONE)<=0 then return end
	Duel.Hint(HINT_SELECTMSG,tp,HINTMSG_SPSUMMON)
	local g=Duel.SelectMatchingCard(tp,c50031699.filter,tp,LOCATION_HAND+LOCATION_DECK,0,1,1,nil,e,tp)
   local tc=g:GetFirst()
	if tc and Duel.SpecialSummonStep(tc,0,tp,tp,false,false,POS_FACEUP) then
		local e1=Effect.CreateEffect(e:GetHandler())
		e1:SetType(EFFECT_TYPE_SINGLE)
		e1:SetCode(EFFECT_DISABLE)
		e1:SetReset(RESET_EVENT+0x1fe0000)
		tc:RegisterEffect(e1,true)
		local e2=Effect.CreateEffect(e:GetHandler())
		e2:SetType(EFFECT_TYPE_SINGLE)
		e2:SetCode(EFFECT_DISABLE_EFFECT)
		e2:SetReset(RESET_EVENT+0x1fe0000)
		tc:RegisterEffect(e2,true)
		local e3=Effect.CreateEffect(e:GetHandler())
		e3:SetType(EFFECT_TYPE_SINGLE)
		e3:SetCode(EFFECT_CANNOT_BE_SYNCHRO_MATERIAL)
		e3:SetProperty(EFFECT_FLAG_UNCOPYABLE)
		e3:SetValue(1)
		e3:SetReset(RESET_EVENT+0x1fe0000)
		tc:RegisterEffect(e3,true)
		local e4=e3:Clone()
		e4:SetCode(EFFECT_CANNOT_BE_FUSION_MATERIAL)
		tc:RegisterEffect(e4,true)
		local e5=e3:Clone()
		e5:SetCode(EFFECT_CANNOT_BE_XYZ_MATERIAL)
		tc:RegisterEffect(e5,true)   
		local e6=e3:Clone()
		e6:SetCode(EFFECT_CANNOT_BE_LINK_MATERIAL)
		tc:RegisterEffect(e6,true)
		  local e7=e3:Clone()
		e7:SetCode(CANNOT_BE_POLARITY_MATERIAL)
		tc:RegisterEffect(e7,true)
		 local e8=e3:Clone()
local e10=e1:Clone()
		e10:SetCode(EFFECT_CANNOT_BE_BIGBANG_MATERIAL)
		tc:RegisterEffect(e10,true)
		e8:SetCode(EFFECT_CANNOT_BE_SPACE_MATERIAL)
		tc:RegisterEffect(e8,true)
		 local e11=e1:Clone()
		e11:SetCode(EFFECT_CANNOT_BE_SPATIAL_MATERIAL)
		tc:RegisterEffect(e11,true)  
		local e12=e1:Clone()
		e12:SetCode(EFFECT_CANNOT_BE_HARMONIZED_MATERIAL)
		tc:RegisterEffect(e12,true)
		local e13=e1:Clone()
		e13:SetCode(EFFECT_CANNOT_BE_BYPATH_MATERIAL)
		tc:RegisterEffect(e13,true)
		local e14=e1:Clone()
		e14:SetCode(EFFECT_CANNOT_BE_TIMELEAP_MATERIAL)
		tc:RegisterEffect(e14,true)
		local e15=e1:Clone()
		e15:SetCode(EFFECT_CANNOT_HAVE_CHROMA_MATERIAL)
		tc:RegisterEffect(e15,true)
		local e16=e1:Clone()
		e16:SetCode(EFFECT_CANNOT_BE_ANNOTEE_MATERIAL)
		tc:RegisterEffect(e16,true)
		local e17=e1:Clone()
		e17:SetCode(EFFECT_CANNOT_BE_ACCENTED_MATERIAL)
		tc:RegisterEffect(e17,true)
		local e18=e1:Clone()
		e18:SetCode(EFFECT_CANNOT_BE_ACCENTED_MATERIAL)
		tc:RegisterEffect(e18,true)
		Duel.SpecialSummonComplete()
	end
end
function c50031699.cfilter(c)
	return not c:IsCode(50031699) and c:IsAbleToDeck()
end

function c50031699.target2(e,tp,eg,ep,ev,re,r,rp,chk,chkc)
	if chkc then return chkc:IsLocation(LOCATION_REMOVED) and chkc:IsControler(tp)  end
	if chk==0 then return Duel.IsPlayerCanDraw(tp,1)
		and Duel.IsExistingTarget(c50031699.cfilter,tp,LOCATION_REMOVED,0,5,nil) end
	Duel.Hint(HINT_SELECTMSG,tp,HINTMSG_TODECK)
	local g=Duel.SelectTarget(tp,c50031699.cfilter,tp,LOCATION_REMOVED,0,5,5,nil)
	Duel.SetOperationInfo(0,CATEGORY_TODECK,g,5,0,0)
	Duel.SetOperationInfo(0,CATEGORY_DRAW,nil,0,tp,1)
end
function c50031699.operation2(e,tp,eg,ep,ev,re,r,rp)
	local tg=Duel.GetChainInfo(0,CHAININFO_TARGET_CARDS)
	if tg:FilterCount(Card.IsRelateToEffect,nil,e)~=5 then return end
	Duel.SendtoDeck(tg,nil,0,REASON_EFFECT)
	local g=Duel.GetOperatedGroup()
	if g:IsExists(Card.IsLocation,1,nil,LOCATION_DECK) then Duel.ShuffleDeck(tp) end
	local ct=g:FilterCount(Card.IsLocation,nil,LOCATION_DECK+LOCATION_EXTRA)
	if ct==5 and g:IsExists(c50031699.cfilterx,1,nil) and Duel.IsPlayerCanDraw(tp,1)  then
		Duel.BreakEffect()
		Duel.Draw(tp,1,REASON_EFFECT)
	end
end
   

function c50031699.cfilterx(c)
	return c:IsLocation(LOCATION_DECK+LOCATION_EXTRA)  and c:IsPreviousPosition(POS_FACEUP) and c:IsSetCard(0x185a) 
end