--Dinobase Capture Bones
local cid,id=GetID()
function cid.initial_effect(c)
	--Activate
	local e1=Effect.CreateEffect(c)
	e1:SetCategory(CATEGORY_NEGATE+CATEGORY_DESTROY)
	e1:SetType(EFFECT_TYPE_ACTIVATE)
	e1:SetCode(EVENT_CHAINING)
	e1:SetCondition(cid.condition)
	e1:SetOperation(cid.activate)
	c:RegisterEffect(e1)
end
function cid.cfilter(c)
	return c:IsFaceup() and c:IsRace(RACE_DINOSAUR)
end
function cid.condition(e,tp,eg,ep,ev,re,r,rp)
	local ph=Duel.GetCurrentPhase()
	return Duel.IsExistingMatchingCard(cid.cfilter,tp,LOCATION_MZONE,0,1,nil)
		and ph>PHASE_MAIN1 and ph<PHASE_MAIN2
end

function cid.activate(e,tp,eg,ep,ev,re,r,rp)
	local tc=eg:GetFirst()
	while tc do
		if tc:IsFaceup() and tc:IsPosition(POS_FACEUP_ATTACK) and tc:IsControler(1-tp) then
			tc:AddCounter(0xc195,1)
		end
 local e1=Effect.CreateEffect(c)
		e1:SetType(EFFECT_TYPE_SINGLE)
		e1:SetProperty(EFFECT_FLAG_SINGLE_RANGE)
		e1:SetCode(EFFECT_CANNOT_ATTACK)
		e1:SetRange(LOCATION_MZONE)
		e1:SetReset(RESET_EVENT+RESETS_STANDARD)
		e1:SetTarget(cid.distg)
		e1:SetTargetRange(0xfe,0xff)
		e1:SetValue(1)
		tc:RegisterEffect(e1)
		local e2=e1:Clone()
		e2:SetCode(EFFECT_UNRELEASABLE_NONSUM)
		tc:RegisterEffect(e2)
		local e3=e1:Clone()
		e3:SetCode(EFFECT_CANNOT_BE_FUSION_MATERIAL)
		tc:RegisterEffect(e3)
		local e4=e1:Clone()
		e4:SetCode(EFFECT_CANNOT_BE_SYNCHRO_MATERIAL)
		tc:RegisterEffect(e4)
		local e5=e1:Clone()
		e5:SetCode(EFFECT_CANNOT_BE_XYZ_MATERIAL)
		tc:RegisterEffect(e5)
		local e6=e1:Clone()
		e6:SetCode(EFFECT_CANNOT_BE_LINK_MATERIAL)
		tc:RegisterEffect(e6)
		local e7=e1:Clone()
		e7:SetCode(EFFECT_CANNOT_BE_EVOLUTE_MATERIAL)
		tc:RegisterEffect(e7)
		local e8=e1:Clone()
		e8:SetCode(EFFECT_CANNOT_BE_POLARITY_MATERIAL)
		tc:RegisterEffect(e8)
		local e9=e1:Clone()
		e9:SetCode(EFFECT_CANNOT_BE_SPACE_MATERIAL)
		tc:RegisterEffect(e9)
		local e10=e1:Clone()
		e10:SetCode(EFFECT_CANNOT_BE_BIGBANG_MATERIAL)
		tc:RegisterEffect(e10)
		local e11=e1:Clone()
		e11:SetCode(EFFECT_CANNOT_BE_SPATIAL_MATERIAL)
		tc:RegisterEffect(e11)  
		local e12=e1:Clone()
		e12:SetCode(EFFECT_CANNOT_BE_HARMONIZED_MATERIAL)
		tc:RegisterEffect(e12)
		local e13=e1:Clone()
		e13:SetCode(EFFECT_CANNOT_BE_BYPATH_MATERIAL)
		tc:RegisterEffect(e13)
		local e14=e1:Clone()
		e14:SetCode(EFFECT_CANNOT_BE_TIMELEAP_MATERIAL)
		tc:RegisterEffect(e14)
		local e15=e1:Clone()
		e15:SetCode(EFFECT_CANNOT_HAVE_CHROMA_MATERIAL)
		tc:RegisterEffect(e15)
		local e16=e1:Clone()
		e16:SetCode(EFFECT_CANNOT_BE_ANNOTEE_MATERIAL)
		tc:RegisterEffect(e16)
		local e17=e1:Clone()
		e17:SetCode(EFFECT_CANNOT_BE_ACCENTED_MATERIAL)
		tc:RegisterEffect(e17)
		local e18=e1:Clone()
		e18:SetCode(EFFECT_CANNOT_BE_ACCENTED_MATERIAL)
		tc:RegisterEffect(e18)
		 local e19=e1:Clone()
		e19:SetCode(EFFECT_CANNOT_CHANGE_POSITION)
		tc:RegisterEffect(e19)
		   local e20=e1:Clone()
		e20:SetCode(EFFECT_CANNOT_ACTIVATE)
		tc:RegisterEffect(e20)
		tc=eg:GetNext()
	end
end

function cid.distg(e,c)
	return c:GetCounter(0xc195)>0 
end